"""
models.py — Database schema definitions for the NewsHere project.

This module defines the SQLAlchemy ORM models representing the project's core data.
It utilizes PostgreSQL features such as 'pgvector' for semantic similarity and 
JSON fields for flexible metadata storage.

Relationships:
- RSSArticle <-> Story (Many-to-Many via StoryArticle)
- RSSArticle <-> ArticleRelationship (Self-referential Many-to-Many)
- Story <-> BiasAnalysisReport (One-to-Many / Cache relationship)
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, DateTime, Integer, Boolean, JSON, ForeignKey, Float, Index
from sqlalchemy.orm import DeclarativeBase, relationship
from pgvector.sqlalchemy import Vector
from database import engine

class Base(DeclarativeBase):
    """Common base for all database models."""
    pass

# ---------------------------------------------------------------------------
# Core Entities
# ---------------------------------------------------------------------------

class RSSArticle(Base):
    """
    Represents a single news article ingested from an RSS feed or GDELT research.
    Stores raw content, AI-generated metadata, and semantic embeddings.
    """
    __tablename__ = "rss_articles"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    outlet = Column(String, nullable=False)
    bias = Column(String, nullable=False)
    country = Column(String, default="IN")
    title = Column(Text, nullable=False)
    url = Column(String, unique=True)
    summary = Column(Text)
    published = Column(String)
    fetched_at = Column(DateTime, default=datetime.utcnow)
    
    # Body management
    body = Column(Text)
    body_fetched = Column(Boolean, default=False)
    content_type = Column(Text)
    fetch_fail_count = Column(Integer, default=0) # Tracks extraction failures for retry logic
    body_quality = Column(Float, default=0.0)    # Score from 0.0-1.0 (scraped vs junk)

    # AI Analysis fields
    ai_summary = Column(Text)
    bias_score = Column(Integer)
    bias_label = Column(String)
    bias_reasoning = Column(Text)
    confidence_score = Column(Float)

    # Semantic representation (384-dimensional dense vector)
    embedding = Column(Vector(384))

class Story(Base):
    """
    Represents a cluster of semantically related articles describing a single event.
    Stores aggregate metrics like diversity and polarization.
    """
    __tablename__ = "stories"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    title = Column(Text, nullable=False)
    summary = Column(Text) # AI-generated story overview
    category = Column(String)
    article_count = Column(Integer, default=0)
    bias_distribution = Column(JSON) # e.g., {"left": 2, "center": 5, "right": 1}
    disagreement_score = Column(Float)
    confidence_score = Column(Float)

    # The geometric center of all article embeddings in the cluster
    centroid_vector = Column(Vector(384))
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # M2M relationship to articles
    articles = relationship(
        "RSSArticle", secondary="story_articles", back_populates="stories")

# ---------------------------------------------------------------------------
# Relationship Tables
# ---------------------------------------------------------------------------

class StoryArticle(Base):
    """
    Associative table linking articles to stories.
    Includes the 'assignment_score' (how well this article fits the story's centroid).
    """
    __tablename__ = "story_articles"

    story_id = Column(String, ForeignKey("stories.id", ondelete="CASCADE"), primary_key=True)
    article_id = Column(String, ForeignKey("rss_articles.id", ondelete="CASCADE"), primary_key=True)
    assignment_score = Column(Float)

class ArticleRelationship(Base):
    """
    Captures cross-source discourse (e.g., Article A contradicts Article B).
    Generated by the AI agent during the cross-examination stage.
    """
    __tablename__ = "article_relationships"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    source_id = Column(String, ForeignKey("rss_articles.id", ondelete="CASCADE"))
    target_id = Column(String, ForeignKey("rss_articles.id", ondelete="CASCADE"))

    relationship_type = Column(String) # e.g., supports, contradicts, expands
    strength = Column(Float)
    evidence = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

# ---------------------------------------------------------------------------
# Monitoring & Maintenance
# ---------------------------------------------------------------------------

class ArticleToRemove(Base):
    """
    Audit log of articles flagged for removal (e.g., dead links, paywalls).
    This serves as a 'black-list' to prevent re-fetching failed URLs.
    """
    __tablename__ = "articles_to_remove"

    id = Column(String, primary_key=True)
    outlet = Column(String)
    url = Column(String)
    reason = Column(Text)
    flagged_at = Column(DateTime, default=datetime.utcnow)

class BiasAnalysisReport(Base):
    """
    Caches the results of deep LangGraph analysis for stories.
    Prevents redundant LLM calls for the same story within a 24-hour window.
    """
    __tablename__ = "bias_analysis_reports"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    story_id = Column(String, nullable=True, index=True)
    topic = Column(String, nullable=False)
    balanced_brief = Column(Text)
    comparison = Column(Text)
    visualization_path = Column(String)
    raw_result = Column(JSON)
    agreement_score = Column(Float)
    is_polarized = Column(Boolean)
    ambiguity_notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

class FetchLog(Base):
    """
    Telemetry log for ingestion jobs (RSS/Body fetching).
    Used for monitoring pipeline health and throughput.
    """
    __tablename__ = "fetch_logs"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    run_id = Column(String)
    outlet = Column(String)
    run_at = Column(DateTime, default=datetime.utcnow)
    articles_new = Column(Integer, default=0)
    articles_skip = Column(Integer, default=0)
    status = Column(String) # e.g., success, partial, error
    error_message = Column(Text)

# ---------------------------------------------------------------------------
# Indices & Back-references
# ---------------------------------------------------------------------------

Index("idx_story_articles_story_id", StoryArticle.story_id)
Index("idx_story_articles_article_id", StoryArticle.article_id)
Index("idx_article_relationships_source", ArticleRelationship.source_id)
Index("idx_article_relationships_target", ArticleRelationship.target_id)

RSSArticle.stories = relationship(
    "Story", secondary="story_articles", back_populates="articles")

def init_db():
    """
    Initializes the database schema. 
    NOTE: Does not handle table migrations. Use Alembic or manual SQL for schema changes.
    """
    Base.metadata.create_all(engine)
