"""
outlets.py — Global registry of news sources and RSS feeds.

This module acts as the single source of truth for all news outlets integrated into 
the NewsHere platform. It categorizes outlets by bias and country, providing the
initial heuristics used by the ingestion pipeline before deep AI analysis.

Structure:
- INDIAN_OUTLETS: Comprehensive list of national and regional Indian sources.
- GLOBAL_OUTLETS: Curated list of international news organizations across 20+ countries.
"""

INDIAN_OUTLETS: dict[str, dict] = {
    "OpIndia": {"bias": "right", "country": "IN", "feeds": ["https://www.opindia.com/feed/"]},
    "Swarajya": {"bias": "right", "country": "IN", "feeds": ["https://swarajyamag.com/feed"]},
    "Organiser": {"bias": "right", "country": "IN", "feeds": ["https://organiser.org/feed/"]},
    "Republic World": {"bias": "right", "country": "IN", "feeds": ["https://www.republicworld.com/rss.xml"]},
    "DNA India": {"bias": "right", "country": "IN", "feeds": ["https://www.dnaindia.com/feeds/india.xml", "https://www.dnaindia.com/feeds/politics.xml"]},
    "The Sunday Guardian": {"bias": "right", "country": "IN", "feeds": ["https://www.sundayguardianlive.com/feed"]},
    "Zee News": {"bias": "right", "country": "IN", "feeds": ["https://zeenews.india.com/rss/india-national-news.xml", "https://zeenews.india.com/rss/politics-news.xml"]},
    "India Today": {"bias": "right", "country": "IN", "feeds": ["https://www.indiatoday.in/rss/1206578", "https://www.indiatoday.in/rss/home"]},
    "Firstpost": {"bias": "right", "country": "IN", "feeds": ["https://www.firstpost.com/rss/india.xml", "https://www.firstpost.com/rss/politics.xml"]},
    "News18": {"bias": "right", "country": "IN", "feeds": ["https://www.news18.com/rss/india.xml", "https://www.news18.com/rss/politics.xml"]},

    "The Wire": {"bias": "left", "country": "IN", "feeds": ["https://thewire.in/rss/politics/feed", "https://thewire.in/rss/law/feed", "https://thewire.in/rss/media/feed"]},
    "Scroll.in": {"bias": "left", "country": "IN", "feeds": ["https://scroll.in/feed"]},
    "The Caravan": {"bias": "left", "country": "IN", "feeds": ["https://caravanmagazine.in/feed"]},
    "Newslaundry": {"bias": "left", "country": "IN", "feeds": ["https://www.newslaundry.com/feed"]},
    "The News Minute": {"bias": "left", "country": "IN", "feeds": ["https://www.thenewsminute.com/rss.xml"]},
    "Article 14": {"bias": "left", "country": "IN", "feeds": ["https://article-14.com/feed"]},
    "Alt News": {"bias": "left", "country": "IN", "feeds": ["https://www.altnews.in/feed/"]},
    "Maktoob Media": {"bias": "left", "country": "IN", "feeds": ["https://maktoobmedia.com/feed/"]},
    "The Leaflet": {"bias": "left", "country": "IN", "feeds": ["https://theleaflet.in/feed/"]},
    "The Citizen": {"bias": "left", "country": "IN", "feeds": ["https://www.thecitizen.in/rss/feed/all"]},

    "The Hindu": {"bias": "center", "country": "IN", "feeds": ["https://www.thehindu.com/news/national/feeder/default.rss"]},
    "Indian Express": {"bias": "center", "country": "IN", "feeds": ["https://indianexpress.com/feed/", "https://indianexpress.com/section/political-pulse/feed/"]},
    "NDTV": {"bias": "center", "country": "IN", "feeds": ["https://feeds.feedburner.com/ndtvnews-india-news", "https://feeds.feedburner.com/ndtvnews-top-stories"]},
    "Times of India": {"bias": "center", "country": "IN", "feeds": ["https://timesofindia.indiatimes.com/rssfeedstopstories.cms"]},
    "Business Standard": {"bias": "center", "country": "IN", "feeds": ["https://www.business-standard.com/rss/politics-current-affairs-10601.rss", "https://www.business-standard.com/rss/current-affairs-10605.rss"]},
    "Economic Times": {"bias": "center", "country": "IN", "feeds": ["https://economictimes.indiatimes.com/rssfeedsdefault.cms", "https://economictimes.indiatimes.com/news/politics-and-nation/rssfeeds/28311565.cms"]},
    "Deccan Herald": {"bias": "center", "country": "IN", "feeds": ["https://www.deccanherald.com/rss-feed/national.rss", "https://www.deccanherald.com/rss-feed/politics.rss"]},
    "The Print": {"bias": "center", "country": "IN", "feeds": ["https://theprint.in/feed/", "https://theprint.in/category/politics/feed/"]},
    "The Quint": {"bias": "center", "country": "IN", "feeds": ["https://www.thequint.com/feed"]},
    "BBC India": {"bias": "center", "country": "IN", "feeds": ["https://feeds.bbci.co.uk/news/world/asia/india/rss.xml"]},
}

GLOBAL_OUTLETS: list[dict] = [
    {"name": "Reuters", "url": "https://www.reutersagency.com/feed/?best-topics=all&post_type=best", "bias": "center", "country": "GL"},
    {"name": "Associated Press", "url": "https://apnews.com/rss", "bias": "center", "country": "GL"},
    {"name": "CNN", "url": "http://rss.cnn.com/rss/edition.rss", "bias": "center", "country": "US"},
    {"name": "New York Times", "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "bias": "center", "country": "US"},
    {"name": "Fox News", "url": "http://feeds.foxnews.com/foxnews/latest", "bias": "right", "country": "US"},
    {"name": "NPR", "url": "https://feeds.npr.org/1001/rss.xml", "bias": "center", "country": "US"},
    {"name": "Bloomberg", "url": "https://feeds.bloomberg.com/markets/news.rss", "bias": "center", "country": "US"},
    {"name": "Wall Street Journal", "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml", "bias": "center", "country": "US"},
    {"name": "Politico", "url": "https://www.politico.com/rss/politics08.xml", "bias": "center", "country": "US"},
    {"name": "Axios", "url": "https://api.axios.com/feed/", "bias": "center", "country": "US"},
    {"name": "TechCrunch", "url": "https://techcrunch.com/feed/", "bias": "center", "country": "US"},
    {"name": "Wired", "url": "https://www.wired.com/feed/rss", "bias": "center", "country": "US"},
    {"name": "BBC News", "url": "http://feeds.bbci.co.uk/news/rss.xml", "bias": "center", "country": "UK"},
    {"name": "BBC World Service", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "bias": "center", "country": "UK"},
    {"name": "The Guardian", "url": "https://www.theguardian.com/world/rss", "bias": "left", "country": "UK"},
    {"name": "Financial Times", "url": "https://www.ft.com/rss/home", "bias": "center", "country": "UK"},
    {"name": "Sky News", "url": "https://feeds.skynews.com/feeds/rss/home.xml", "bias": "center", "country": "UK"},
    {"name": "The Economist", "url": "https://www.economist.com/latest/rss.xml", "bias": "center", "country": "UK"},
    {"name": "The Telegraph", "url": "https://www.telegraph.co.uk/rss.xml", "bias": "center", "country": "UK"},
    {"name": "The Independent", "url": "https://www.independent.co.uk/news/world/rss", "bias": "center", "country": "UK"},
    {"name": "OpenDemocracy", "url": "https://www.opendemocracy.net/en/rss.xml", "bias": "left", "country": "UK"},
    {"name": "Politico Europe", "url": "https://www.politico.eu/feed/", "bias": "center", "country": "UK"},
    {"name": "CBC News", "url": "https://www.cbc.ca/cmlink/rss-topstories", "bias": "center", "country": "CA"},
    {"name": "Global News", "url": "https://globalnews.ca/feed/", "bias": "center", "country": "CA"},
    {"name": "Toronto Star", "url": "https://www.thestar.com/content/thestar/feed.RSSManagerServlet.articles.topstories.rss", "bias": "center", "country": "CA"},
    {"name": "CTV News", "url": "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009", "bias": "center", "country": "CA"},
    {"name": "National Post", "url": "https://nationalpost.com/feed/", "bias": "center", "country": "CA"},
    {"name": "The Globe and Mail", "url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/", "bias": "center", "country": "CA"},
    {"name": "Maclean's", "url": "https://www.macleans.ca/feed/", "bias": "center", "country": "CA"},
    {"name": "Financial Post", "url": "https://financialpost.com/feed/", "bias": "center", "country": "CA"},
    {"name": "BNN Bloomberg Canada", "url": "https://www.bnnbloomberg.ca/polopoly_fs/1.1!/feed/rss.xml", "bias": "center", "country": "CA"},
    {"name": "CityNews", "url": "https://toronto.citynews.ca/feed/", "bias": "center", "country": "CA"},
    {"name": "NHK World", "url": "https://www3.nhk.or.jp/rss/news/cat0.xml", "bias": "center", "country": "JP"},
    {"name": "The Japan Times", "url": "https://www.japantimes.co.jp/feed/", "bias": "center", "country": "JP"},
    {"name": "Nikkei Asia", "url": "https://asia.nikkei.com/rss/feed/nar", "bias": "center", "country": "JP"},
    {"name": "Yonhap News Agency", "url": "https://en.yna.co.kr/RSS/news.xml", "bias": "center", "country": "KR"},
    {"name": "Korea Herald", "url": "http://www.koreaherald.com/common_prog/rssdisp.php?ct=020000000000.xml", "bias": "center", "country": "KR"},
    {"name": "Channel NewsAsia", "url": "https://www.channelnewsasia.com/rssfeeds/8395986", "bias": "center", "country": "SG"},
    {"name": "The Straits Times", "url": "https://www.straitstimes.com/news/world/rss.xml", "bias": "center", "country": "SG"},
    {"name": "Bangkok Post", "url": "https://www.bangkokpost.com/rss/data/topstories.xml", "bias": "center", "country": "TH"},
    {"name": "Jakarta Post", "url": "https://www.thejakartapost.com/feed", "bias": "center", "country": "ID"},
    {"name": "Philippine Daily Inquirer", "url": "https://newsinfo.inquirer.net/feed", "bias": "center", "country": "PH"},
    {"name": "Anadolu Agency", "url": "https://www.aa.com.tr/en/rss/default?cat=guncel", "bias": "center", "country": "TR"},
    {"name": "Daily Sabah", "url": "https://www.dailysabah.com/rss", "bias": "center", "country": "TR"},
    {"name": "Hürriyet", "url": "https://www.hurriyetdailynews.com/rss", "bias": "center", "country": "TR"},
    {"name": "TRT World", "url": "https://www.trtworld.com/rss.xml", "bias": "center", "country": "TR"},
    {"name": "Yeni Şafak", "url": "https://www.yenisafak.com/rss", "bias": "center", "country": "TR"},
    {"name": "O Globo", "url": "https://oglobo.globo.com/rss.xml", "bias": "center", "country": "BR"},
    {"name": "Folha de S.Paulo", "url": "https://feeds.folha.uol.com.br/internacional/en/world/rss091.xml", "bias": "center", "country": "BR"},
    {"name": "Estadão", "url": "https://www.estadao.com.br/rss/ultimas.xml", "bias": "center", "country": "BR"},
    {"name": "G1 Globo", "url": "https://g1.globo.com/rss/g1/", "bias": "center", "country": "BR"},
    {"name": "UOL Notícias", "url": "https://rss.uol.com.br/feed/noticias.xml", "bias": "center", "country": "BR"},
    {"name": "The Star Malaysia", "url": "https://www.thestar.com.my/rss/news/nation", "bias": "center", "country": "MY"},
    {"name": "Malay Mail", "url": "https://www.malaymail.com/feed/rss", "bias": "center", "country": "MY"},
    {"name": "Bernama", "url": "https://www.bernama.com/en/rss.php", "bias": "center", "country": "MY"},
    {"name": "Free Malaysia Today", "url": "https://www.freemalaysiatoday.com/feed/", "bias": "center", "country": "MY"},
    {"name": "New Straits Times", "url": "https://www.nst.com.my/rss", "bias": "center", "country": "MY"},
    {"name": "Tempo", "url": "https://en.tempo.co/rss", "bias": "center", "country": "ID"},
    {"name": "Antara News", "url": "https://en.antaranews.com/rss", "bias": "center", "country": "ID"},
    {"name": "Detik News", "url": "https://rss.detik.com/index.php/detikcom", "bias": "center", "country": "ID"},
    {"name": "Kompas", "url": "https://rss.kompas.com/rss", "bias": "center", "country": "ID"},
    {"name": "Punch Nigeria", "url": "https://punchng.com/feed/", "bias": "center", "country": "NG"},
    {"name": "Vanguard Nigeria", "url": "https://www.vanguardngr.com/feed/", "bias": "center", "country": "NG"},
    {"name": "Premium Times", "url": "https://www.premiumtimesng.com/feed", "bias": "center", "country": "NG"},
    {"name": "The Guardian Nigeria", "url": "https://guardian.ng/feed/", "bias": "center", "country": "NG"},
    {"name": "ThisDay Live", "url": "https://www.thisdaylive.com/feed/", "bias": "center", "country": "NG"},
    {"name": "News24", "url": "https://www.news24.com/news24/rss", "bias": "center", "country": "ZA"},
    {"name": "Mail & Guardian", "url": "https://mg.co.za/feed/", "bias": "center", "country": "ZA"},
    {"name": "TimesLIVE", "url": "https://www.timeslive.co.za/rss/", "bias": "center", "country": "ZA"},
    {"name": "BusinessTech", "url": "https://businesstech.co.za/news/feed/", "bias": "center", "country": "ZA"},
    {"name": "Independent Online", "url": "https://www.iol.co.za/rss", "bias": "center", "country": "ZA"},
    {"name": "Xinhua", "url": "http://www.xinhuanet.com/english/rss/worldrss.xml", "bias": "center", "country": "CN"},
    {"name": "China Daily", "url": "http://www.chinadaily.com.cn/rss/world_rss.xml", "bias": "center", "country": "CN"},
    {"name": "Global Times", "url": "https://www.globaltimes.cn/rss/outbrain.xml", "bias": "center", "country": "CN"},
    {"name": "CGTN", "url": "https://news.cgtn.com/news/rss/index.xml", "bias": "center", "country": "CN"},
    {"name": "Sixth Tone", "url": "https://www.sixthtone.com/feeds/news", "bias": "center", "country": "CN"},
    {"name": "Dawn", "url": "https://www.dawn.com/feeds/home", "bias": "center", "country": "PK"},
    {"name": "Geo News", "url": "https://www.geo.tv/rss/1/0", "bias": "center", "country": "PK"},
    {"name": "The News International", "url": "https://www.thenews.com.pk/rss/1/10", "bias": "center", "country": "PK"},
    {"name": "Express Tribune", "url": "https://tribune.com.pk/feed", "bias": "center", "country": "PK"},
    {"name": "Press TV", "url": "https://www.presstv.ir/rss/rss.xml", "bias": "center", "country": "IR"},
    {"name": "Tehran Times", "url": "https://www.tehrantimes.com/rss", "bias": "center", "country": "IR"},
    {"name": "Tasnim News", "url": "https://www.tasnimnews.com/en/rss", "bias": "center", "country": "IR"},
    {"name": "RT News", "url": "https://www.rt.com/rss/", "bias": "center", "country": "RU"},
    {"name": "TASS", "url": "https://tass.com/rss/v2.xml", "bias": "center", "country": "RU"},
    {"name": "Sputnik News", "url": "https://sputniknews.com/export/rss2/archive/index.xml", "bias": "center", "country": "RU"},
]
